# Generated by Django 6.0.3 on 2026-03-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_alter_products_user_alter_formet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='Gst_enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='default_gst',
            field=models.IntegerField(default=0),
        ),
    ]
