# Generated by Django 6.0.3 on 2026-04-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_sells_product_gst_sells_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='Inv_subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='Customer_mobile',
            field=models.IntegerField(),
        ),
    ]
