# Generated by Django 6.0.3 on 2026-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0008_invoice_inv_subtotal_alter_customer_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Inv_Total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Inv_additional_charges',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Inv_discount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Inv_gst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Inv_internal_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='Inv_subtotal',
            field=models.FloatField(),
        ),
    ]
